---
- name: My super playbook
  hosts: all
  become: yes

  vars: 
   mytext: "Privet from Tauren Milfs"

  tasks:
  - name: Ping test
    ping:

  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml
