---
- name: My Super Playbook new
  hosts: all
  become: yes

  vars: 
   mytext: "Dopriy den"
 
  tasks: 
  - name: Ping test
    ping:

  - name: Unregister Server from Loadbalance
    shell: echo this server {{ inventory_hostname }} was deregister form our loadbalancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1 #запустить на ансибл+сервер (локалхост)

  - name: Update my DB
    shell: echo UPDATING database...
    run_once: true #запустит один раз

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is file 1
        On English Hello
        On Ukranian {{ mytext }}
    delegate_to: linux1  # запустить только на линукс1

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is file 2
        On English Hello
        On Ukranian {{ mytext }}

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my server will come up online
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
